### ISSUE TITLE
Placeholder text not appearing in IE10

### ISSUE THREAD

**Issue by pdscti** [AlfonsoML/confighelper#14]
I'm using the config helper through Drupal to add placeholder text to a ckeditor field. When viewed using Chrome, the placeholder text appears without issue. When using IE10, it is not visible.

**Comment by AlfonsoML** [comment]
Have you tested IE11?
Can you create a simple demo to test the problem?

**Comment by pdscti** [comment]
Not sure what you mean by a simple demo?

**Comment by pdscti** [comment]
Works in IE 11.

**Comment by AlfonsoML** [comment]
A simple demo means a page with a textarea, a normal version of CKEditor + this plugin, so we can be sure that there's nothing else causing problems and that I can use to debug step by step and understand why it fails for you.
I think that I've tested with older versions of IE, but maybe you've used a different configuration, something has changed in CKEditor or my tests were wrong, but I prefer to have a page that should always fail instead of wasting my time with something that it isn't a real problem.

**Comment by pdscti** [comment]
I've used the ckeditor customiser to add the add-on, and its running through a Drupal site and the WYSIWYG module: before I set up all that, do YOU have a simple demo set up for the plug in that I can test on? :)

**Comment by AlfonsoML** [comment]
here's one old demo:
http://alfonsoml.blogspot.com.es/2012/04/placeholder-text-in-ckeditor.html

2015-01-20 17:03 GMT+01:00 pdscti <notifications@github.com>:

**Comment by pdscti** [comment]
Works on that demo, so unless the code has significantly changed I'd guess its something to do with the Drupal integration. I'm guessing you won't want to get into that, so I'll let the developers know.
